name: Run Script

on:
  push:

jobs:
  checks:
    name: "Script"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install 7-Zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - run: pip install -r requirements.txt

      - name: Extract the archive
        run: |
          mkdir extracted
          7z x uncensored_lib.7z -oextracted/

      - name: Run Script
        run: python my_script.py

      - name: Create an archive
        run: |
          7z a uncensored_lib.7z extracted/

      - uses: actions/upload-artifact@v4
        with:
          path: extracted/
          compression-level: 9
